config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD


  devise_for :users, :path => 'accounts'


=======
  devise_for :users, :path => 'accounts'
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
  resources :users do
  	resources :boards do
  		resources :pins
  	end
  end
  root 'users#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
<<<<<<< HEAD
	belongs_to :user 
	#has_and_belongs_to_many :pins 
	has_many :pins 
=======
  belongs_to :user
  has_many :pins
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
end

app/models/pin.rb
class Pin < ActiveRecord::Base
<<<<<<< HEAD
	#has_and_belongs_to_many :boards 
	belongs_to :board
	belongs_to :user
=======
  belongs_to :user
  belongs_to :board
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
<<<<<<< HEAD

  #attr_accessible :name
  has_many :boards
  has_many :pins, through: :boards 

=======
  has_many :boards
  
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def index
<<<<<<< HEAD
		@boards=Board.all
	end


	def show
		@user=current_user
		@board=Board.find params[:id]
		@pins=Pin.where(board_id:)
		
=======
		@users=User.all 
		@boards=current_user.boards
		@boards_public=[]
		@boards_private=[]

		@users.each do |user|
			@user=user
			@boards_from_other_user=user.boards
			@boards_from_other_user.each do |board_from_other|
				if(board_from_other.public==true)
					@boards_public<<board_from_other
				end
			end

		end

		
		@boards.each do |board|
			
			if board.public==true 
				unless @boards_public.include?(board)
					@boards_public<<board
				end
			else
				@boards_private<<board
			end 
		end
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

	end

	def create
		@user=current_user
<<<<<<< HEAD
		@board=current_user.boards.build(board_params)
		@board.user_id=@user.id

		if @board.save
			redirect_to user_board_path(current_user,@board)
		else
			render 'new'
		end
	end



	def edit
		@board=Board.find params[:id]
	end

	def new
		@board=Board.new 

	end

	def destroy
		@board=Board.find params[:id]
		@board.destroy

		redirect_to user_boards_path 
	end


	def update
		@board=current_user.boards.find(params[:id])
		if @board.update(board_params)
			redirect_to user_board_path(current_user,@board)
=======
		@board=@user.boards.new(board_params)
		@board.user_id=current_user.id 

		if @board.save
			redirect_to user_board_path(@user.id,@board.id)
		else
			render 'new'
		end

	end

	def show
		@board = Board.find params[:id]

		if !@board.public? && @board.user != current_user
			redirect_to :root, alert: "You cannot access that board"
		end
		@pins=@board.pins
	end



	def edit
		@board=current_user.boards.find params[:id]
	end



	def new
		@board=current_user.boards.new
	end



	def update
		@board=current_user.boards.find params[:id]
		if @board.update(board_params)
			redirect_to user_board_path(current_user, @board.id)
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
		else
			render 'edit'
		end
	end

<<<<<<< HEAD



	private
	def board_params
			params.require(:board).permit(:name, :description, :public)
		end
	



=======
	def destroy
		@board=current_user.boards.find params[:id]
		@board.destroy 

		redirect_to user_boards_path(current_user)
	end

	private
	def board_params
		params.require(:board).permit(:name, :description, :public)
		end
	
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
<<<<<<< HEAD
	def index
		@pins=Pin.all 
	end

	def show
		@pin=Pin.find params[:id]
	end

	def edit
		@pin=Pin.find params[:id]
	end

	def update
		@pin=Pin.find params[:id]

		if @pin.update(pin_params)
			redirect_to @pin 

		else
			render 'edit'
		end

	end



	def new
		@pin=Pin.new 
	end


	def create
		@board=Board.find(params[:board_id])
		@pin=@board.pins.new(pin_params)
		if @pin.save
			redirect_to @pin
		else
			render 'new'
		end
	end

	def destroy
		@pin=Pin.find params[:id]
		@pin.destroy
		redirect_to pins_path 

=======
	def create
		@user=current_user
		@board=current_user.boards.find(params[:board_id])
		@pin=@board.pins.new(pins_params)
		@pin.user_id=@user.id
		if @pin.save
			redirect_to user_board_pin_path(current_user,@board.id,@pin.id)
		else
			render 'new'
		end
		
	end

	def show

		@pin=Pin.find params[:id]
		@user=@pin.user
		@board=@user.boards.find(params[:board_id])
		#@board=current_user.boards.find(params[:board_id])
		#@pin=@board.pins.find params[:id]





	end


	def index
		@board=current_user.boards.find(params[:board_id])
		@pins=@board.pins 
	end


	def edit
		@board=current_user.boards.find(params[:board_id])
		@pin=@board.pins.find params[:id]
	end


	def destroy
		@board=current_user.boards.find(params[:board_id])
		@pin=@board.pins.find params[:id]
		@pin.destroy
		redirect_to user_board_path(current_user,@board.id)
	end

	def new
		@board=current_user.boards.find(params[:board_id])
		@pin=@board.pins.new
	end

	def update 
		@board=current_user.boards.find(params[:board_id])
		@pin=@board.pins.find params[:id]
		if @pin.update(pins_params)
			redirect_to user_board_pin_path(current_user,@board.id,@pin.id)
		else
			render 'edit'
		end
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
	end


	private
<<<<<<< HEAD
	def pin_params
		params.require(:pin).permit(:title, :description, :url, :likes)		
=======
	def pins_params
		params.require(:pin).permit(:title, :description, :url, :likes, :subtitle, :url2, :url3, :url4)
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
<<<<<<< HEAD
  	@users=User.all
=======
  	@users=User.all 
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_for([current_user, @board]) do |f| %>

	<p>
	<%= f.label :name %> <br>
	<%= f.text_area :name%> 
	</p>

	<p>
	<%= f.label :description %> <br>
	<%= f.text_area :description %> 
	</p>

	<p>
	<br><%= f.label "Public"%> </br>
	<%=f.check_box :public, {:checked=>true}%>
	</p>

	<p>
	<%= f.submit %>
	</p>

<% end %>

app/views/boards/edit.html.erb
<<<<<<< HEAD
edit.html.erb
=======
<h1>Edit Your Board</h1>
<%=render 'form'%>
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/boards/index.html.erb
<<<<<<< HEAD
<h2>Index of the Boards </h2>
<p>This is current user's email:
<%=current_user.email%></p>

<%counter=0%>
<br>Name of the Board</br>
<%@boards.each do |board|%>
	<%counter+=1%>
	<br><%=board.name%></br>
	<%=link_to 'Show', user_board_path(current_user, board)%>
	<%=link_to 'Edit', edit_user_board_path(current_user,board)%>
	
	<%=link_to 'Delete', user_board_path(current_user, board), method: :delete, data: {confirm:"Do you really want to delete Board?"} %>
	<%end%>

<p>
The number of the Board:
<%=counter%>
</p>

<p>
<%=link_to 'Create', new_user_board_path(current_user)%>
</p>
=======
<h1>Welcome to Your Boards!</h1>
<p>Creator of the Board:<%=current_user.email%> </p>
<% boardnumber=0%>
<br><h2>Private</h2></br>
<% @boards_private.each do |board| %>
	<%boardnumber+=1%>
	<h4><%=board.name%></h4>
		<%=link_to 'Show', user_board_path(current_user,board.id) %>
		<%=link_to 'Edit', edit_user_board_path(current_user, board.id)%>
		<%=link_to 'Delete', user_board_path(current_user,board.id), method: :delete, data: {confirm:"Do you really want to delete Board?"} %> </br>
	<%end%>

<br>Number of the private boards: <%=boardnumber%> </br>


<% public_board_number=0%>
<br><h2>Public</h2></br>
<% @boards_public.each do |board| %>
	<%public_board_number+=1%>
	<h6>[Creator: <%=@users.find(board.user_id).email%>]</h6>
	<h4><%=board.name%></h4>

	
	<%=link_to 'Show', user_board_path(current_user,board.id) %>
	<%if @users.find(board.user_id)==current_user%>
		<%=link_to 'Edit', edit_user_board_path(current_user, board.id)%>
		<%=link_to 'Delete', user_board_path(current_user,board.id), method: :delete, data: {confirm:"Do you really want to delete Board?"} %> </br>
	<%end%>

<%end%>
<br>Number of the public boards: <%=public_board_number%> </br>
<br>Total Number of the boards: <%=public_board_number+boardnumber%> </br>
<br><%=link_to 'Create a new Board', new_user_board_path(current_user)%>


>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/boards/new.html.erb
<<<<<<< HEAD
new.html.erb
=======

<h2>Create New Board!</h2>
<%=render 'form'%>
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/boards/show.html.erb
<<<<<<< HEAD
<h2>Welcome to the show page of the <%=@board.name%></h2>

<%pin=0%>

<p>These are your pins in the Board! </p>

<%@pins.each do |pin|%>
	<br><%=pin.title%></br>
	<%= image_tag(pin.url, width: "30%", height: "30%") %>
	<%=link_to 'EditPin', edit_user_board_pin_path(:user_id,:board_id)%>
	<%=link_to 'DeletePin', user_board_pin_path(:user_id,:board_id), method: :delete, data: {confirm:"Do you really want to delete this Pin?"} %>
<%end%>

<br><%=link_to 'AddPin', new_user_board_pin_path(:user_id,:board_id)%></br>
=======

<h1><%=@board.name%></h1>
<%pinnumber=0%>



<%@pins.each do |pin|%>
	<br><%=pin.title%></br>
	<br><%= link_to image_tag(pin.url, width: "30%", height: "30%"), user_board_pin_path(current_user,@board.id,pin.id) %></br>

	<% if @board.user==current_user %>
		<%=link_to 'EditPin', edit_user_board_pin_path(current_user,@board.id, pin.id)%>,
		<%=link_to 'DeletePin', user_board_pin_path(current_user,@board.id, pin.id), method: :delete, data: {confirm:"Do you really want to delete this Pin?"} %><br>
	<%end%>
<%end%>

<% if @board.user==current_user %>
	<%=link_to 'Create a new Pin', new_user_board_pin_path(current_user,@board.id)%>
<%end%>
	<br><%=link_to 'Boards List', user_boards_path(current_user)%></br>

>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/layouts/application.html.erb
<!DOCTYPE html>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<html>
<head>
  <title>Pinterestingbru</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<<<<<<< HEAD
=======

>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<<<<<<< HEAD
=======



>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e
<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<<<<<<< HEAD
<%= form_for @pin do |f| %>
 
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pin.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

   <p>
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </p>
 


  <p>
    <%= f.submit %>
  </p>
 
<% end %>
=======
<%= form_for([current_user, @board, @pin]) do |f| %>

	<p>
	<%= f.label :title %> <br>
	<%= f.text_area :title%> 
	</p>

	<p>
	<%= f.label :subtitle %> <br>
	<%= f.text_area :subtitle%> 
	</p>

	<p>
	<%= f.label :description %> <br>
	<%= f.text_area :description %> 
	</p>

	<p>
	<%= f.label :url%> <br>
	<%= f.text_area :url%> 
	</p>

	<p>
	<%= f.label :url2%> <br>
	<%= f.text_area :url2%> 
	</p>

	<p>
	<%= f.label :url3%> <br>
	<%= f.text_area :url3%> 
	</p>

	<p>
	<%= f.label :url4%> <br>
	<%= f.text_area :url4%> 
	</p>


	<p>
	<%= f.submit %>
	</p>

<% end %>


>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/pins/create.html.erb
create.html.erb

app/views/pins/edit.html.erb
<<<<<<< HEAD
edit.html.erb
=======
<h2>Edit your Pin</h2>
<%=render 'form'%>
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/pins/index.html.erb
index.html.erb

app/views/pins/new.html.erb
<<<<<<< HEAD
<h2>Add new Pin!</h2>

<%= render 'form' %>
=======

<h1> Add a new Pin</h1>
<%=render 'form'%>
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/pins/newpin.html.erb
newpin.html.erb

app/views/pins/show.html.erb
<<<<<<< HEAD
show.html.erb
=======


<h1><%=@pin.title%> </h1>
<h3><%=@pin.subtitle%></h3>
<br><%=@pin.description%></br>
<br><%= image_tag(@pin.url, width: "30%", height: "30%") %></br>
<br><%= image_tag(@pin.url2, width: "30%", height: "30%") %></br>
<br><%= image_tag(@pin.url3, width: "30%", height: "30%") %></br>
<br><%= image_tag(@pin.url4, width: "30%", height: "30%") %></br>


<%=link_to 'Board', user_board_path(current_user,@board.id) %>
<%=link_to 'Edit', edit_user_board_pin_path(current_user, @board.id, @pin.id)%>
<%=link_to 'Delete',user_board_pin_path(current_user,@board.id, @pin.id), method: :delete, data: {confirm:"Do you really want to delete the pin?"} %>
>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e

app/views/users/index.html.erb
<<<<<<< HEAD
<h1>User#index</h1>
<%=link_to 'Index of the Boards', user_boards_path(current_user)%>
=======
<h1>Users#index</h1>
<p><%=link_to 'Index of Your Board', user_boards_path(current_user)%> </p>

>>>>>>> 236044ed06d85d2750b48bd1e543b20e7ecd009e